# Generated by Django 2.1.2 on 2018-11-04 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type_product',
            field=models.BooleanField(),
        ),
    ]
