# Generated by Django 2.1.2 on 2018-12-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='code',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='is_required',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='is_unique',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='type_attr',
        ),
        migrations.AddField(
            model_name='attribute',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product_attribute',
            name='lock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product_category',
            name='lock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rating',
            name='confirm_bought',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='sex',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='purchase_service_ads',
            name='state',
            field=models.CharField(choices=[('1', 'Success'), ('0', 'Cancel'), ('2', 'IsPosted'), ('3', 'IsConfirmed'), ('4', 'IsActiving'), ('5', 'Expired')], max_length=1),
        ),
        migrations.AlterField(
            model_name='rating',
            name='is_activity',
            field=models.BooleanField(default=True),
        ),
    ]
