# Generated by Django 2.1.2 on 2018-12-06 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_service',
            name='amount',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
