# Generated by Django 2.1.2 on 2018-12-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20181204_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='product_id',
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='archive_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='see',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_type',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
