# Generated by Django 2.1.2 on 2018-10-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20181008_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='q_post',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='q_vip',
            field=models.IntegerField(default=0),
        ),
    ]
