# Generated by Django 2.1.2 on 2018-11-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20181114_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_product',
            name='is_index',
        ),
        migrations.AddField(
            model_name='post_product',
            name='is_lock',
            field=models.BooleanField(default=False),
        ),
    ]
