# Generated by Django 2.1.2 on 2018-12-08 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20181206_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='token_ghtk',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
