# Generated by Django 2.1.2 on 2018-12-07 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_product_category_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product_attribute',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
