# Generated by Django 2.1.2 on 2018-11-22 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20181116_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_product',
            name='bought',
            field=models.IntegerField(default=0),
        ),
    ]
