# Generated by Django 2.1.2 on 2018-12-08 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_order_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_detail',
            name='version',
        ),
    ]
