# Generated by Django 2.1.2 on 2018-12-09 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_order_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('1', 'Thành công'), ('0', 'Hủy bỏ'), ('2', 'Đặt hàng')], max_length=1),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='state',
            field=models.CharField(choices=[('1', 'Thành công'), ('0', 'Hủy bỏ'), ('2', 'Đặt hàng'), ('3', 'Đang gói hàng'), ('4', 'Đang vận chuyển')], max_length=1),
        ),
    ]
