# Generated by Django 2.1.2 on 2018-12-10 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20181209_0345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating_Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_star', models.IntegerField()),
                ('confirm_bought', models.BooleanField()),
                ('is_activity', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cus', to='website.Account')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mer', to='website.Account')),
            ],
        ),
    ]
