# Generated by Django 2.1.2 on 2018-12-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_rating_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_detail',
            name='discount',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
