# Generated by Django 2.1.2 on 2018-12-12 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_order_detail_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='peter', max_length=200),
            preserve_default=False,
        ),
    ]
