# Generated by Django 2.1.2 on 2018-12-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='code_act_ads',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='comment',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
