# Generated by Django 2.0.6 on 2018-12-15 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20181213_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_10', models.BooleanField(default=False)),
                ('is_50', models.BooleanField(default=False)),
                ('is_100', models.BooleanField(default=False)),
                ('is_daily_7', models.BooleanField(default=False)),
                ('is_daily_15', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Account')),
            ],
        ),
        migrations.AlterField(
            model_name='service_ads_post',
            name='state',
            field=models.CharField(choices=[('1', 'IsPosting'), ('2', 'IsConfirm'), ('0', 'Cancel')], max_length=1),
        ),
    ]
